packages:
  - .

autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: false
preferSymlinkedExecutables: true

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  koffi: true
  node-pty: true
  protobufjs: true
